# Generated by Django 5.2.8 on 2025-11-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualemission',
            name='activity',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='annualemission',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='annualemission',
            name='emission_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
