# Generated by Django 5.2.8 on 2025-11-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_annualemission_activity_annualemission_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualemission',
            name='activity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='annualemission',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='annualemission',
            name='emission_type',
            field=models.CharField(max_length=255),
        ),
    ]
